language: generic
sudo: false
addons:
  apt:
    sources:
      - ubuntu-elisp
    packages:
      - emacs23-gtk
script:
  - emacs --version
  - emacs -batch --eval
    "(progn (setq byte-compile-error-on-warn t) (batch-byte-compile))"
    .emacs.el
