language: generic
sudo: false
addons:
  apt:
    packages:
    - emacs
script:
  - emacs --version
  - emacs -batch --eval
    "(progn (setq byte-compile-error-on-warn t) (batch-byte-compile))"
    .emacs.el
