sudo: false
language: emacs-lisp

env:
  - EMACS=emacs
  - EMACS=emacs23
  - EMACS=emacs24

install: true

addons:
  apt:
    packages:
      - $EMACS

script:
  - emacs --version
  - emacs -batch -f batch-byte-compile .emacs.el
