sudo: required
language: generic
env:
  - EMACS=emacs
  - EMACS=emacs23
  - EMACS=emacs24
install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
script:
  - emacs --version
  - emacs -batch --eval "(progn (batch-byte-compile))" .emacs.el
